disqus: ## Your disqus_shortname, e.g. username
uyan: ## Your uyan_id. e.g. 1234567
livere: ## Your livere data-uid, e.g. MTAyMC8zMDAxOC78NTgz
changyan: ## Your changyan appid, e.g. cyrALsXc8
changyan_conf: ## Your changyan conf, e.g. prod_d8a508c2825ab57eeb43e7c69bba0e8b
gitment:
  enable: false ## If you want to use Gitment comment system please set the value to true.
  owner: ## Your GitHub ID, e.g. username
  repo: ## The repository to store your comments, make sure you're the repo's owner, e.g. imsun.github.io
  client_id: ## GitHub client ID, e.g. 75752dafe7907a897619
  client_secret: ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
gitalk:
  enable: true ## 启用 Gitalk 评论系统
  owner: luzhongqiu ## Your GitHub ID
  repo: luzhongqiu.github.io ## 存储评论的仓库名
  client_id: ## 需要填写你的 GitHub OAuth App ID
  client_secret: ## 需要填写你的 GitHub OAuth App Secret
  admin: luzhongqiu ## GitHub 用户名
valine: ## https://valine.js.org
  enable: false ## If you want to use Valine comment system, please set the value to true.
  appid: ## Your LeanCloud application App ID, e.g. pRBBL2JR4N7kLEGojrF0MsSs-gzGzoHsz
  appkey: ## Your LeanCloud application App Key, e.g. tjczHpDfhjYDSYddzymYK1JJ
  notify: false ## Mail notifier, see https://github.com/xCss/Valine/wiki/Valine-评论系统中的邮件提醒设置
  verify: false ## Validation code.
  placeholder: 说点什么吧... ## Comment box placeholders.
  avatar: 'mp' ## Gravatar type
  pageSize: 10 ## Number of comments per page.
  guest_info: nick,mail,link ## Attributes of reviewers.

google_search: true ## Use Google search, true/false.
baidu_search: false ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: true ## 启用本地搜索
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
fancybox: true ## 启用图片灯箱效果
show_category_count: true ## 显示分类计数
toc_number: true ## 目录显示序号
shareto: true ## 启用分享按钮
busuanzi: true ## 启用不蒜子访问统计
wordcount: true ## 启用字数统计
widgets_on_small_screens: true ## 小屏幕显示侧边栏
canvas_nest:
  enable: true ## 启用动态背景
  color: "100,99,98" ## RGB 颜色值
  opacity: "0.7" ## 透明度
  zIndex: "-1" ## 层级
  count: "150" ## 线条数量
donate:
  enable: false ## 打赏按钮
  github: 
  alipay_qr: 
  wechat_qr: 
  btc_qr: 
  btc_key: 
  paypal_url: 
post_copyright:
  enable: true ## 启用文章版权信息
  author: LJM
  copyright_text: 本文由 LJM 创作，采用 知识共享署名 4.0 国际许可协议进行许可。<br>转载请注明作者及出处。

menu:
  - page: 首页
    directory: .
    icon: fa-home
  - page: 归档
    directory: archives/
    icon: fa-archive
  - page: 关于
    directory: about/
    icon: fa-user
  - page: 订阅
    directory: atom.xml
    icon: fa-rss

widgets: ## 侧边栏组件
  - search
  - category
  - tag
  - recent_posts
  - links

links:
  - title: GitHub
    url: https://github.com/luzhongqiu
  - title: 中宇云网
    url: http://www.yunwangst.com

timeline:
  - num: 1
    word: 2017/03-开始写博客
  - num: 2
    word: 2018/06-老九门
  - num: 3
    word: 2025/02-博客装修
  - num: 4
    word: More

# Static files
js: js
css: css

# Theme version
version: 1.0.0
